site_name: Pipeline v0 - Doc Técnica
theme:
  name: material
  palette:
    scheme: slate
    primary: teal

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: ["."]
          options:
            show_if_no_docstring: true 
            annotations_path: brief
          

nav:
  - Proyecto: index.md
  - API & Datos:
      - Endpoints (Main): api_main.md
      - Modelos y BBDD: api_db.md
  - Redis: 
    - Schemas: schemas.md
    - Mensajeria: messaging.md
  - Pipeline (Procesamiento):
      - Orquestador: pipeline_core.md
      - Fase 0 (Escaneo): phase_0.md
      - Fase 1 (Hashing): phase_1.md
      - Fase 2 (Extracción): phase_2.md
      - Fase 3 (IA/OCR): phase_3.md
  - Configuración: config.md 
  - Helpers: helpers.md